### ISSUE TITLE
RuntimeError: shape '[1280, 1280, 3, 3]' is invalid for input of size 11077178

### ISSUE THREAD

**Issue by banMo88** [TheLastBen/PPS#1]
The notebook works well on the free machine. But after I updated, this bug occurs.

Loading weights [973cb455d0] from /notebooks/temp/hassakuHentaiModel_v11.safetensors
loading stable diffusion model: RuntimeError
Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 195, in initialize
    modules.sd_models.load_model()
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 424, in load_model
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 271, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 250, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/usr/local/lib/python3.9/dist-packages/safetensors/torch.py", line 100, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: shape '[1280, 1280, 3, 3]' is invalid for input of size 11077178

Stable diffusion model failed to load, exiting

**Comment by banMo88** [comment]
Never mind.I upload a wrong model.
