### ISSUE TITLE
Paperspace error

### ISSUE THREAD

**Issue by AmaryII1s** [TheLastBen/PPS#12]
I do not really understand anything about how it works, was running TheLastBen/PPS on free gpus on paperspace for about 2 weeks. But today i got this error.
Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 29, in <module>
    import gradio
  File "/usr/local/lib/python3.9/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 35, in <module>
    from gradio.blocks import Block, BlockContext
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 20, in <module>
    from gradio_client import serializing
  File "/usr/local/lib/python3.9/dist-packages/gradio_client/__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "/usr/local/lib/python3.9/dist-packages/gradio_client/client.py", line 21, in <module>
    from huggingface_hub import SpaceStage
ImportError: cannot import name 'SpaceStage' from 'huggingface_hub' (/usr/local/lib/python3.9/dist-packages/huggingface_hub/__init__.py)

And BEFORE THIS ERROR i was issued with this one: 
NameError: name "'sd'" is not defined

**Comment by AmaryII1s** [comment]
I guess it resolved by itself with some time... Got some extra options to choose from on Paperspace. Maybe they are edding something new. Sorry for disturbing

**Comment by TheLastBen** [comment]
make sure you use the latest notebooks that you can find inside the folder "latest_notebooks" (copy them to the main folder)

**Comment by thefixinhixon** [comment]
I'm getting this same error as well. I'm also seeing there is a gradio outage. Related?

**Comment by thefixinhixon** [comment]
> I'm getting this same error as well. I'm also seeing there is a gradio outage. Related?

deleting my notebook and making a fresh one seems to have resolved the issue
