### ISSUE TITLE
My Stable Diffusion checkpoints are not opening in Stable Diffusion

### ISSUE THREAD

**Issue by Juansigma** [TheLastBen/PPS#5]
![image](https://user-images.githubusercontent.com/127377346/236657283-b4c06775-a415-47f5-a24c-5e35d35d2817.png)

![image](https://user-images.githubusercontent.com/127377346/236657205-e8ee6b13-8f0e-4560-a33c-95c63624bf3d.png)

This is the line of code that appears when I try to load a Stable Diffusion checkpoint:

Loading weights [287e5942a8] from /notebooks/sd/stable-diffusion-webui/models/Stable-diffusion/Latte.safetensors
changing setting sd_model_checkpoint to Latte.safetensors [287e5942a8]: RuntimeError
Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/modules/shared.py", line 509, in set
    self.data_labels[key].onchange()
  File "/notebooks/sd/stable-diffusion-webui/modules/call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 205, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()))
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 505, in reload_model_weights
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 271, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 250, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/usr/local/lib/python3.9/dist-packages/safetensors/torch.py", line 100, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: shape '[5120, 640]' is invalid for input of size 764992

**Comment by Juansigma** [comment]
I solved the problem :)
Just use that command you sent me with the models folder link
